repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe, --quiet, -l120]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.0.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
        language_version: python3
        exclude: setup.cfg
    -   id: end-of-file-fixer
        language_version: python3
        exclude: setup.cfg
    -   id: fix-encoding-pragma
        language_version: python3
        args: [--remove]
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language_version: python3
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus, '--application-directories=.:src']
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.18.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.0
    hooks:
    -   id: rst-backticks
