repos:
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
        args: [--safe, --quiet, -l120]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3
        exclude: setup.cfg
    -   id: end-of-file-fixer
        language_version: python3
        exclude: setup.cfg
    -   id: fix-encoding-pragma
        language_version: python3
        args: [--remove]
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language_version: python3
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus, '--application-directories=.:src']
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --keep-mock]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
